### ISSUE TITLE
DOC: rasterize_image with MergeAlg.add always returns dataset with only NaN's

### ISSUE THREAD

**Issue by BENR0** [corteva/geocube#110] opened 2022-06-14 08:19 UTC
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
import geopandas as gpd
import functools
from geocube.api.core import make_geocube
from geocube.rasterize import rasterize_image
from rasterio.enums import MergeAlg

ra_image = functools.partial(rasterize_image, merge_alg=MergeAlg.add)

gdfdata = gpd.read_file(
    "https://github.com/corteva/geocube/blob/master/test/test_data/input/time_vector_data.geojson",
    crs="epsg:4326",
)

gdfdata["test_attr"] = gdfdata["test_attr"].div(gdfdata["test_attr"]).astype({"test_attr": "int16"})

test = make_geocube(
    vector_data=gdfdata,
    measurements=["test_attr"],
    datetime_measurements=None,
    interpolate_na_method=None,
    resolution=[0.1, 0.1],
    rasterize_function=ra_image
)
```
#### Problem description

I have a point dataset which I want to rasterize. There are multiple points for each target pixel. I want to "sum" up the values of all points in that pixel while rasterizing. 

#### Expected Output

If the rasterize_image function is used with `merge_alg=MergeAlg.add` each pixel in the resulting dataset should contain the sum of the values of all points that fall within that pixel.

#### Environment Information

geocube v0.1.2.dev0

GDAL deps:
         fiona: 1.8.21
   GDAL[fiona]: 3.4.1
      rasterio: 1.2.10
GDAL[rasterio]: 3.3.2

Python deps:
       appdirs: 1.4.4
         click: 8.0.4
      datacube: 1.8.6
     geopandas: 0.10.2
     rioxarray: 0.10.2
        pyproj: 3.3.0
        xarray: 2022.3.0

System:
        python: 3.8.12 (default, Sep 13 2021, 09:11:55)  [GCC 9.1.0]
       executable: /bin/python3
       machine: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.2.5

#### Installation method
 - pip

**Comment by BENR0** [comment] 2022-06-14 08:36
It seems that this is related to the default fill value being NaN. If I set a integer fill value it looks like it is working. In this case, while not directly a bug anymore, I will still leave this issue open since I recon this should be documented a little better somehow.

**Comment by snowman2** [comment] 2022-06-14 13:14
A PR with an example is welcome.

Duplicate of #28

**Closed** 2022-06-14 13:16 UTC
Labels: question, documentation
